import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
type Props = { searchParams: Promise<{ iskanje?: string }> };
export default async function DobaviteljiPage({ searchParams }: Props) {
  const { iskanje = "" } = await searchParams; const supabase = await createClient();
  const { data: token, error: authError } = await supabase.auth.getClaims(); if (authError || !token?.claims?.sub) redirect("/prijava");
  let query = supabase.from("dobavitelj").select("id, naziv, kratica, telefonska_stevilka, email, naslov, spletna_stran").order("naziv");
  if (iskanje.trim()) query = query.or(`naziv.ilike.%${iskanje.trim()}%,kratica.ilike.%${iskanje.trim()}%`);
  const { data: dobavitelji, error } = await query;
  return <main className="min-h-screen bg-slate-100"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><div><p className="text-sm font-semibold uppercase text-slate-500">Materiali</p><h1 className="text-xl font-bold text-slate-900">Dobavitelji</h1></div><Link href="/materiali" className="rounded-lg border border-slate-300 px-4 py-2 text-sm text-slate-700">Nazaj na katalog</Link></div></header><section className="mx-auto max-w-7xl px-6 py-10"><div className="mb-7 flex items-end justify-between gap-4"><div><h2 className="text-3xl font-bold text-slate-900">Pregled dobaviteljev</h2><p className="mt-2 text-slate-600">V katalogu je {dobavitelji?.length ?? 0} dobaviteljev.</p></div><Link href="/materiali/dobavitelji/nov" className="rounded-lg bg-slate-900 px-5 py-2.5 font-semibold text-white">Dodaj dobavitelja</Link></div><form className="mb-6 flex gap-3 rounded-xl border border-slate-200 bg-white p-4"><input name="iskanje" defaultValue={iskanje} placeholder="Poišči po nazivu ali kratici" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2.5 text-slate-900"/><button className="rounded-lg bg-slate-900 px-5 py-2.5 font-semibold text-white">Poišči</button>{iskanje && <Link href="/materiali/dobavitelji" className="rounded-lg border border-slate-300 px-5 py-2.5 text-slate-700">Počisti</Link>}</form>{error ? <p className="rounded-xl bg-red-50 p-4 text-red-700">Dobaviteljev ni bilo mogoče naložiti.</p> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full text-left"><thead className="bg-slate-50"><tr>{["Naziv", "Kratica", "Telefon", "E-pošta", "Dejanja"].map(x => <th key={x} className="px-5 py-3 text-sm text-slate-700">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-200">{(dobavitelji ?? []).map(d => <tr key={d.id}><td className="px-5 py-4 font-medium text-slate-900">{d.naziv}</td><td className="px-5 py-4 text-slate-700">{d.kratica ?? "—"}</td><td className="px-5 py-4 text-slate-700">{d.telefonska_stevilka ?? "—"}</td><td className="px-5 py-4 text-slate-700">{d.email ?? "—"}</td><td className="px-5 py-4"><Link href={`/materiali/dobavitelji/${d.id}/uredi`} className="rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-700">Uredi</Link></td></tr>)}</tbody></table></div>}</section></main>;
}
