import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { ustvariDobavitelja } from "./actions";
type Vrednosti = { naziv?: string; kratica?: string | null; telefonska_stevilka?: string | null; email?: string | null; naslov?: string | null; spletna_stran?: string | null };
type Props = { searchParams: Promise<{ napaka?: string }> };
export default async function NovDobaviteljPage({ searchParams }: Props) { const supabase = await createClient(); const { data: token, error } = await supabase.auth.getClaims(); if (error || !token?.claims?.sub) redirect("/prijava"); const { napaka } = await searchParams; return <Obrazec naslov="Nov dobavitelj" action={ustvariDobavitelja} sporocilo={napaka ? "Preveri podatke in poskusi znova." : null}/>; }
export function Obrazec({ naslov, action, sporocilo, vrednosti = {} }: { naslov: string; action: (data: FormData) => void | Promise<void>; sporocilo: string | null; vrednosti?: Vrednosti }) {
  const input = "mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 text-slate-900";
  return <main className="min-h-screen bg-slate-100"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4"><div><p className="text-sm font-semibold uppercase text-slate-500">Materiali · Dobavitelji</p><h1 className="text-xl font-bold text-slate-900">{naslov}</h1></div><Link href="/materiali/dobavitelji" className="rounded-lg border border-slate-300 px-4 py-2 text-sm text-slate-700">Prekliči</Link></div></header><section className="mx-auto max-w-4xl px-6 py-10"><form action={action} className="rounded-2xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-2xl font-bold text-slate-900">Podatki dobavitelja</h2>{sporocilo && <p className="mt-6 rounded-lg bg-red-50 px-4 py-3 text-red-700">{sporocilo}</p>}<div className="mt-7 grid gap-6 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700 sm:col-span-2">Naziv *<input name="naziv" required defaultValue={vrednosti.naziv} autoFocus className={input}/></label><label className="text-sm font-medium text-slate-700">Kratica<input name="kratica" defaultValue={vrednosti.kratica ?? ""} className={input}/></label><label className="text-sm font-medium text-slate-700">Telefonska številka<input name="telefon" defaultValue={vrednosti.telefonska_stevilka ?? ""} className={input}/></label><label className="text-sm font-medium text-slate-700">E-poštni naslov<input name="email" type="email" defaultValue={vrednosti.email ?? ""} className={input}/></label><label className="text-sm font-medium text-slate-700">Spletna stran<input name="spletnaStran" defaultValue={vrednosti.spletna_stran ?? ""} className={input}/></label><label className="text-sm font-medium text-slate-700 sm:col-span-2">Naslov<textarea name="naslov" defaultValue={vrednosti.naslov ?? ""} rows={3} className={input}/></label></div><div className="mt-8 flex justify-end gap-3 border-t border-slate-200 pt-6"><Link href="/materiali/dobavitelji" className="rounded-lg border border-slate-300 px-5 py-2.5 text-slate-700">Prekliči</Link><button className="rounded-lg bg-slate-900 px-5 py-2.5 font-semibold text-white">Shrani dobavitelja</button></div></form></section></main>;
}
